name: Build Android APK

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Expo Prebuild
        working-directory: ./frontend
        run: npx expo prebuild -p android --clean

      - name: Build APK
        working-directory: ./frontend/android
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FamilyWallet-APK
          path: frontend/android/app/build/outputs/apk/release/app-release.apk
